# Generated by Django 3.1.7 on 2021-04-04 18:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skin',
            new_name='HairDiary',
        ),
        migrations.RenameModel(
            old_name='Hair',
            new_name='SkinDiary',
        ),
    ]
