# Generated by Django 3.1.7 on 2021-04-08 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0007_skindiary_supplements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cleanser', models.TextField(max_length=100)),
                ('Toner', models.TextField(max_length=100)),
                ('Serum', models.TextField(max_length=100)),
                ('Cream', models.TextField(max_length=100)),
                ('Lotion', models.TextField(max_length=100)),
                ('Mask', models.TextField(max_length=100)),
                ('Eye', models.TextField(max_length=100)),
                ('Sunscreen', models.TextField(max_length=100)),
                ('Oil', models.TextField(max_length=100)),
                ('Exfoliatior', models.TextField(max_length=100)),
                ('Peel', models.TextField(max_length=100)),
                ('Shampoo', models.TextField(max_length=100)),
                ('Conditioner', models.TextField(max_length=100)),
                ('Scrub', models.TextField(max_length=100)),
                ('Leavein', models.TextField(max_length=100)),
                ('Dry', models.TextField(max_length=100)),
                ('Spray', models.TextField(max_length=100)),
                ('Rinse', models.TextField(max_length=100)),
                ('Protectant', models.TextField(max_length=100)),
                ('Balm', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=100)),
                ('Brand', models.TextField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vitamins', models.TextField(max_length=100)),
                ('Oil', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
