# Generated by Django 3.1.7 on 2021-04-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_pill_products_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='Roller',
            field=models.TextField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pill',
            name='Tool',
            field=models.TextField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
