# Generated by Django 3.1.7 on 2021-04-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210408_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pill',
            old_name='Oil',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='pill',
            name='Roller',
        ),
        migrations.RemoveField(
            model_name='pill',
            name='Tool',
        ),
        migrations.RemoveField(
            model_name='pill',
            name='Vitamins',
        ),
        migrations.AddField(
            model_name='pill',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
