# Generated by Django 3.1.7 on 2021-04-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210408_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='Cream',
            new_name='Mist',
        ),
        migrations.RenameField(
            model_name='routine',
            old_name='Lotion',
            new_name='Moisturizer',
        ),
    ]
